### PR TITLE
updated miniExclude to point to the renamed 'tests' directory

### PR DESCRIPTION
**Pull request by modcoms**
'grunt build' is failing on a fresh install: 
...
Building Dojo...

> > Error
> > Warning: Task "dojo:dist" failed. Use --force to continue.
> > ...
> > from the build log:
> > ...
> > error(307) Failed to evaluate module tagged as pure AMD (fell back to processing with regular expressions).
> >     module: dojogen/tests/dojoConfig; error: ReferenceError: location is not defined

Due to the directory name change on the last commit, tests are now added to the built version. I've updated the miniExclude resource to reflect the directory name change.

### CODE REVIEW

**Comment by modcoms** [comment]
added a README update fixing some broken links.

**Comment by bryanforbes** [comment]
Thanks for the pull request! I know I haven't added it to the README yet, but have you signed a [Dojo Foundation CLA](http://dojofoundation.org/about/claForm)? All contributions to this project need to be covered by one. If you haven't, please sign one and let me know what name or email address you used to sign it. Thanks!

**Comment by modcoms** [comment]
Hi Bryan, yes it's already on file: martin@modcoms.com

**Comment by bryanforbes** [comment]
Thank you! I have committed the fix.

**Comment by modcoms** [comment]
np Bryan, an excellent project - good luck with it (I'll be trying it out
for sure).

Martin

**Pull request closed without merging**
